import React from "react";

export const nobotContent = [
    <img src={require('../pics/project/nobot/homepage.png')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
    <img src={require('../pics/project/nobot/email.png')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
]

export const speakerContent = [
    <img src={require('../pics/project/speaker/amp.png')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
    <img src={require('../pics/project/speaker/board.png')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
    <img src={require('../pics/project/speaker/fasteners.png')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
    <img src={require('../pics/project/speaker/exciter.png')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
    <video controls src={require('../speaker.mov')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />
]

export const watererContent = [
    <img src={require('../pics/project/waterer/parts.jpg')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
    <img src={require('../pics/project/waterer/wiring.jpg')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
    <img src={require('../pics/project/waterer/diagram.png')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
    <img src={require('../pics/project/waterer/motor_setup.jpg')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
    <video controls src={require('../pics/project/waterer/no_plants.MOV')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
    <img src={require('../pics/project/waterer/final_setup.jpg')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />,
    <video controls src={require('../pics/project/waterer/final.mov')} style={{
        maxWidth: "80vw",
        maxHeight: "80vh",
        display: "block",
        margin: "0 auto",
        position: "relative",
        top: "50%",
        transform: "translateY(10%)",
    }} />
]